### ISSUE TITLE
Can you provide an example input.txt file?

### ISSUE THREAD

**Issue by yidiwang21** [jbujak/A-star-CUDA#1]

**Comment by jbujak** [comment]
Sure, input description and examples are provided in attached assignment.
[cuda.pdf](https://github.com/jbujak/A-star-CUDA/files/4718809/cuda.pdf)

**Comment by yidiwang21** [comment]
> Sure, input description and examples are provided in attached assignment.
> [cuda.pdf](https://github.com/jbujak/A-star-CUDA/files/4718809/cuda.pdf)

Thank you!
