### ISSUE TITLE
Test file?

### ISSUE THREAD

**Issue by cjardin** [jbujak/A-star-CUDA#2]
Hello,

I am sorry to even ask, but would it be possible for you to commit a test pathfinding input file?

Thank you!

Cary

**Comment by jbujak** [comment]
Hi, Cary!

I uploaded full assignment text with in/out description and example inputs at https://github.com/jbujak/A-star-CUDA/blob/master/assignment.pdf

Best,
Jakub

**Comment by cjardin** [comment]
Hi Jakub,

Thank you very much!!!

Cary

**Comment by cjardin** [comment]
Hi Jakub,

I have a map SOOO big.. :)

It breaks the linker.. Trying to malloc.. If you you wanna see, try a map of 22,000 x 22,000

Thank you again for your code! And that is one hell of a Master’s course assignment 


Cary
